### ISSUE TITLE
Add subscribe_to as association

### ISSUE THREAD

**Issue by roman-dubrovsky** [Set27/RailsDZrepo#3]
`subscribe_to` по факту, тоже ассоциация на таблицу юзеров. Это кстати есть и в задании

https://github.com/Set27/RailsDZrepo/blob/3855fb319980c82c1f6515921fab440f80df2508/app/models/subscribe.rb#L1-L3

**Comment by Set27** [comment]
Закрыл коммитом [Refactor subscribes, create second assosiations] (https://github.com/Set27/RailsDZrepo/commit/5f70be7f68ae982069d361d3fa8a25e7215ea917)

**Comment by roman-dubrovsky** [comment]
Добавил коммент https://github.com/Set27/RailsDZrepo/commit/5f70be7f68ae982069d361d3fa8a25e7215ea917

+ нет, ты еще не добавил ассоциацию

**Comment by Set27** [comment]
> Добавил коммент [5f70be7](https://github.com/Set27/RailsDZrepo/commit/5f70be7f68ae982069d361d3fa8a25e7215ea917)
> 
>     * нет, ты еще не добавил ассоциацию

`t.index ["sub_to_id"], name: "index_subscribes_on_sub_to_id"
    t.index ["user_id"], name: "index_subscribes_on_user_id"`

А это разве не ассосиации? Зачем мне два раза прописывать belongs_to на одну и туже таблицу?

**Comment by roman-dubrovsky** [comment]
хаха. Так ассоциации то разные

**Comment by Set27** [comment]
> хаха. Так ассоциации то разные

А можно ссылку где объясняется как можно сделать нормальную ассоциасию на два поля в таблице? Я совсем запутался
